a = 10
b = 20
if a < b:
    print(f"{a} is less than {b}") 
else:
    print(f"{a} is not less than {b}")
if a <= b:
    print(f"{a} is less than or equal to {b}") 
else:
    print(f"{a} is not less than or equal to {b}")
if a > b:
    print(f"{a} is greater than {b}")
else:
    print(f"{a} is not greater than {b}") 
if a >= b:
    print(f"{a} is greater than or equal to {b}")
else:
    print(f"{a} is not greater than or equal to {b}")