# This program calculates the area of a rectangle

# Defining the length and width of the rectangle
length = 8
width = 8

# Calculating the area
area = length * width

# Display result
print("Rectangle is:", area)

'''
In this program:
- 1ST define the length and width of the rectangle.
- 2ND we calculate the area by multiplying length and width.
- Finally, the result is printed to the console.
'''

# End of the program
